<?php
$z[0]=Array("spaceurl","",145,163);
$z[0][4]=array();
$z[1]=Array("face","",192,205);
$z[1][4]=array();
$z[2]=Array("spaceurl","",246,264);
$z[2][4]=array();
$z[3]=Array("uname","",283,297);
$z[3][4]=array();
$z[4]=Array("spaceurl","",334,352);
$z[4][4]=array();
$z[5]=Array("spaceurl","",405,423);
$z[5][4]=array();
$z[6]=Array("spaceurl","",487,505);
$z[6][4]=array();
$z[7]=Array("rankname","",622,640);
$z[7][4]=array();
$z[8]=Array("jointime","",702,754);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",816,869);
$z[9][4]=array();
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>